###
# curl --location 'http://localhost:8080/api/v1/movies'
#--header 'Content-Type: application/json'
#--data '{
#    "title": "movie111",
#    "year": 1999,
#    "genre": "Comedy"
#}'
POST http://localhost:8080/api/v1/movies
Content-Type: application/json

{
  "title": "movie44",
  "year": 1999,
  "genre": "Comedy"
}

### invalid request
POST http://localhost:8080/api/v1/movies
Content-Type: application/json

{
  "title": "movie44",
  "year": 180,
  "genre": "Comedy"
}

###
# curl --location 'http://localhost:8080/api/v1/movies/2'
GET http://localhost:8080/api/v1/movies/2

###
# curl --location 'http://localhost:8080/api/v1/movies'
GET http://localhost:8080/api/v1/movies?page=0&size=2


###
# curl --location --request PUT 'http://localhost:8080/api/v1/movies/2'
#--header 'Content-Type: application/json'
#--data '{
#  "title": "movie111_updated",
#  "year": 1999,
#  "genre": "Comedy"
#}'
PUT http://localhost:8080/api/v1/movies/5
Content-Type: application/json

{
  "title": "movie222_updated",
  "year": 299,
  "genre": "Comedy"
}

###
DELETE http://localhost:8080/api/v1/movies/3

###
GET http://localhost:8080/api/v1/movies/search?title=movie111&page=0&size=2









