spring.application.name=Qwen_pet_movie_catalog

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

#cache properties
app.cache.ttl.movies-default=10m
app.cache.global_prefix=movie:
app.cache.ttl.movies-by-id=10m
app.cache.ttl.movies-list=5m
app.cache.ttl.movies-search=5m

# OMDb API: http://www.omdbapi.com/?i=tt3896198&apikey=9f037f28
external.omdb.api-key=${EXTERNAL_OMDB_API_KEY:}
external.omdb.base-url=https://www.omdbapi.com

# Logging
logging.level.com.krev.qwen_pet_movie_catalog.external=debug
logging.level.feign=debug
logging.level.io.github.openfeign=debug

###
# Resilience4j: CircuitBreaker
# usually this is 50-100
resilience4j.circuitbreaker.instances.omdbApi.sliding-window-size=10
resilience4j.circuitbreaker.instances.omdbApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.omdbApi.wait-duration-in-open-state=10s

# Resilience4j: Retry
resilience4j.retry.instances.omdbApi.max-attempts=3
resilience4j.retry.instances.omdbApi.wait-duration=1s
# to define set of exceptions that has to be retried, for example:
resilience4j.retry.instances.omdbApi.retry-exceptions[0]=feign.RetryableException
resilience4j.retry.instances.omdbApi.retry-exceptions[1]=java.net.UnknownHostException
resilience4j.retry.instances.omdbApi.retry-exceptions[2]=java.net.ConnectException
resilience4j.retry.instances.omdbApi.retry-exceptions[3]=java.io.IOException
resilience4j.retry.instances.omdbApi.retry-exceptions[4]=java.lang.RuntimeException

# Logging Resilience4j
logging.level.io.github.resilience4j=DEBUG
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.level.io.github.resilience4j.retry=DEBUG
###