# we can define variable and its default value
# it helps us to override these variables (DB_HOST, DB_NAME) in docker-compose file (environment properties)
spring.datasource.url=jdbc:postgresql://{DB_HOST:postgres}:5432/${DB_NAME:movie_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.redis.host=${REDIS_HOST:movie-redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

# Safe settings for Docker
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=validate

# Logging (less details than locally)
logging.level.com.krev.qwen_pet_movie_catalog.external=INFO
logging.level.feign=INFO
logging.level.io.github.openfeign=INFO
logging.level.io.github.resilience4j=INFO
logging.level.io.github.resilience4j.circuitbreaker=INFO
logging.level.io.github.resilience4j.retry=INFO

# OMDb API:
external.omdb.api-key=${EXTERNAL_OMDB_API_KEY:}
external.omdb.base-url=${EXTERNAL_OMDB_BASE_URL:https://www.omdbapi.com}