-- auto-generated definition
create table movie
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6),
    genre       varchar(255),
    title       varchar(255) not null,
    updated_at  timestamp(6),
    year        integer,
    director    varchar(255),
    imdb_rating varchar(255),
    plot        varchar(255),
    poster      varchar(255)
);